version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample-node-app:latest   # ✅ Add this line
    container_name: sample-node-app
    ports:
      - "9000:9000"
    restart: unless-stopped

