version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample-node-app:latest
    container_name: sample-node-app
    ports:
      - "9001:9000"
    env_file:
      - .env   # 👈 This line loads your environment variables
    restart: unless-stopped


